version: "3.3"

services:
  redis:
    container_name: redis_cool_tasks
    image: "redis:latest"
  postgres:
    container_name: postgres_cool_tasks
    image: "postgres:latest"  
    ports:
     - "5432:5432"
    volumes:
     - ./init-db.sh:/docker-entrypoint-initdb.d/1-init-db.sh
     #- ./create-tables.sql:/docker-entrypoint-initdb.d/2-create-tables.sql
  cool_tasks:
    container_name: cool_tasks
    image: cool_tasks:latest
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
